//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "chunk")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub x: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub y: i32,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub terrain: Vec<u8>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::colony::Entity")]
    Colony,
    #[sea_orm(has_one = "super::colony_chunk::Entity")]
    ColonyChunk,
    #[sea_orm(has_many = "super::object::Entity")]
    Object,
}

impl Related<super::colony_chunk::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColonyChunk.def()
    }
}

impl Related<super::object::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Object.def()
    }
}

impl Related<super::colony::Entity> for Entity {
    fn to() -> RelationDef {
        super::colony_chunk::Relation::Colony.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::colony_chunk::Relation::Chunk.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
