//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "colony")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub origin_chunk_x: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub origin_chunk_y: i32,
    pub user_id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chunk::Entity",
        from = "(Column::OriginChunkX, Column::OriginChunkY)",
        to = "(super::chunk::Column::X, super::chunk::Column::Y)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chunk,
    #[sea_orm(has_many = "super::colony_chunk::Entity")]
    ColonyChunk,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::colony_chunk::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColonyChunk.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::chunk::Entity> for Entity {
    fn to() -> RelationDef {
        super::colony_chunk::Relation::Chunk.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::colony_chunk::Relation::Colony.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
