//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "colony_chunk")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chunk_x: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chunk_y: i32,
    pub colony_x: i32,
    pub colony_y: i32,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chunk::Entity",
        from = "(Column::ChunkX, Column::ChunkY)",
        to = "(super::chunk::Column::X, super::chunk::Column::Y)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chunk,
    #[sea_orm(
        belongs_to = "super::colony::Entity",
        from = "(Column::ColonyX, Column::ColonyY)",
        to = "(super::colony::Column::OriginChunkX, super::colony::Column::OriginChunkY)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Colony,
}

impl Related<super::chunk::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chunk.def()
    }
}

impl Related<super::colony::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Colony.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
