//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "object")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub kind: i16,
    #[sea_orm(column_type = "JsonBinary")]
    pub data: Json,
    pub chunk_x: i32,
    pub chunk_y: i32,
    pub x: i16,
    pub y: i16,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::chunk::Entity",
        from = "(Column::ChunkX, Column::ChunkY)",
        to = "(super::chunk::Column::X, super::chunk::Column::Y)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Chunk,
}

impl Related<super::chunk::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chunk.def()
    }
}

impl Related<super::colony::Entity> for Entity {
    fn to() -> RelationDef {
        super::chunk::Relation::Colony.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::chunk::Relation::Object.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
