//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub discord_id: Option<String>,
    #[sea_orm(unique)]
    pub username: String,
    pub permissions: i64,
    pub rate_limit_infractions: i16,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::colony::Entity")]
    Colony,
}

impl Related<super::colony::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Colony.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
